import '../styles/globals.css'
import type {AppProps} from 'next/app'
import Head from 'next/head'
import {Fragment} from 'react'

function MyApp({Component, pageProps}: AppProps) {
    return <Fragment>
        <Head>
            <title>Informational App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500&display=swap" rel="stylesheet"/>
        </Head>
        <Component {...pageProps} />
    </Fragment>
}

export default MyApp
