import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import {Fragment} from 'react'

function MyApp({ Component, pageProps }: AppProps) {
  return <Fragment>
    <Head>
      <title>Informational App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </Fragment>
}

export default MyApp
